[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW-FROM https://www.arpi-be.com"
    Content-Security-Policy = "frame-ancestors 'self' https://arpi-org.com https://www.arpi-org.com https://arpi-be.com https://www.arpi-be.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
